export const categories = [
  "Automotive",
  "Books and Literature",
  "Business and Finance",
  "Careers",
  "Education",
  "Events and Attractions",
  "Family and Relationships",
  "Fine Art",
  "Food & Drink",
  "Healthy Living",
  "Hobbies & Interests",
  "Home & Garden",
  "Medical Health",
  "Movies",
  "Music and Audio",
  "News and Politics",
  "Personal Finance",
  "Pets",
  "Pop Culture",
  "Real Estate",
  "Religion & Spirituality",
  "Science",
  "Shopping",
  "Sports",
  "Style & Fashion",
  "Technology & Computing",
  "Television",
  "Travel",
  "Video Gaming",
];
